#!/usr/bin/env python3
## Fully generated by chatgpt

from __future__ import annotations

import csv
import sys
import math
from pathlib import Path
from typing import Dict, List, Tuple, Optional

csv.field_size_limit(sys.maxsize)

DATASETS = [
    ("torres-2023-100", r"\TorresOld{}"),
    ("torres-2025-100", r"\TorresNew{}"),
    ("cws-10k-85", r"\NewEightyFive{}"),
]

OUTPUT_DIR = "reproduced_tables"


def read_csv(path: Path) -> List[Dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"Missing file: {path}")

    with path.open("r", encoding="utf-8-sig", newline="") as f:
        sample = f.read(4096)
        f.seek(0)

        try:
            dialect = csv.Sniffer().sniff(sample, delimiters=",;\t")
        except csv.Error:
            dialect = csv.excel
            dialect.delimiter = ";"

        return list(csv.DictReader(f, dialect=dialect))

def normalize_boolish(value: object) -> bool:
    if value is None:
        return False
    s = str(value).strip().lower()
    return s in {"1", "true", "yes", "y", "t"}


def parse_int(value: object, default: int = 0) -> int:
    if value is None:
        return default
    s = str(value).strip()
    if s == "":
        return default
    try:
        return int(float(s))
    except ValueError:
        return default


def find_column(columns: List[str], candidates: List[str]) -> Optional[str]:
    lowered = {c.lower(): c for c in columns}
    for candidate in candidates:
        if candidate.lower() in lowered:
            return lowered[candidate.lower()]
    return None


def latex_escape(text: str) -> str:
    replacements = {
        "&": r"\&",
        "%": r"\%",
        "_": r"\_",
        "#": r"\#",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text


def percent_str(num: int, den: int) -> str:
    if den == 0:
        return "0.0\\% (0/0)"
    pct = round((num / den) * 100, 1)
    return f"{pct:.1f}\\% ({num}/{den})"


def percent_str_md(num: int, den: int) -> str:
    if den == 0:
        return "0.0% (0/0)"
    pct = round((num / den) * 100, 1)
    return f"{pct:.1f}% ({num}/{den})"


def compute_leak_metrics(dataset_dir: Path) -> Dict[str, int]:
    """
    Reads leaks_type/ulti-merge.csv and computes:
    - to_any_endpoints
    - to_analytics_endpoints
    - to_telemetry_endpoints

    Assumptions:
    - there is one row per wallet
    - boolean-like leak columns exist
    - analytics? and telemetry? may exist exactly with those names
    - total leakage is computed as: wallet leaks to any endpoint if ANY boolean-like leak column is true
    """
    path = dataset_dir / "analysis_result" / "leaks_type" / "ulti-merge.csv"
    rows = read_csv(path)

    if not rows:
        return {
            "to_any_endpoints": 0,
            "to_analytics_endpoints": 0,
            "to_telemetry_endpoints": 0,
        }

    columns = list(rows[0].keys())

    analytics_col = find_column(columns, ["analytics?"])
    telemetry_col = find_column(columns, ["telemetry?"])

    # Detect boolean leak columns conservatively.
    # We exclude obvious identifier / metadata columns.
    excluded_keywords = {
        "id",
        "name",
        "extension",
        "wallet",
        "address",
        "dataset",
        "version",
        "file",
        "path",
        "count",
        "total",
    }

    candidate_bool_cols: List[str] = []
    for col in columns:
        col_lower = col.lower().strip()
        if col_lower in {"analytics?", "telemetry?"}:
            candidate_bool_cols.append(col)
            continue
        if col_lower.endswith("?"):
            candidate_bool_cols.append(col)
            continue
        if any(keyword == col_lower for keyword in excluded_keywords):
            continue

    # Remove duplicates while preserving order.
    seen = set()
    bool_cols = []
    for c in candidate_bool_cols:
        if c not in seen:
            bool_cols.append(c)
            seen.add(c)

    # If no '?' columns were found, try a fallback:
    # use any column that looks boolean across all rows.
    if not bool_cols:
        for col in columns:
            values = {str(r.get(col, "")).strip().lower() for r in rows}
            if values.issubset({"", "0", "1", "true", "false", "yes", "no"}):
                bool_cols.append(col)

    to_any = 0
    to_analytics = 0
    to_telemetry = 0

    for row in rows:
        if analytics_col and normalize_boolish(row.get(analytics_col)):
            to_analytics += 1
        if telemetry_col and normalize_boolish(row.get(telemetry_col)):
            to_telemetry += 1

        leaks_any = any(normalize_boolish(row.get(col)) for col in bool_cols)
        if leaks_any:
            to_any += 1

    return {
        "to_any_endpoints": to_any,
        "to_analytics_endpoints": to_analytics,
        "to_telemetry_endpoints": to_telemetry,
    }


def compute_domain_metrics(dataset_dir: Path) -> Dict[str, object]:
    """
    Reads tracker_presence/wallet_leak_domains.csv and computes:
    - total_domains_receiving_addresses
    - contacted_by_only_one_wallet
    - contacted_by_only_one_wallet_pct
    - top_5_domains: list[(domain, count)]

    Assumptions:
    - one row per domain
    - there is a column unique_extensions_with_wallet_leak
    - there is a domain-like column such as domain / hostname
    """
    path = dataset_dir / "analysis_result" / "tracker_presence" / "wallet_leak_domains.csv"
    rows = read_csv(path)

    if not rows:
        return {
            "total_domains_receiving_addresses": 0,
            "contacted_by_only_one_wallet": 0,
            "top_5_domains": [],
        }

    columns = list(rows[0].keys())
    count_col = find_column(columns, ["unique_extensions_with_wallet_leak"])

    if count_col is None:
        raise ValueError(
            f"Could not find 'unique_extensions_with_wallet_leak' in {path}. "
            f"Found columns: {columns}"
        )

    domain_col = find_column(columns, ["domain", "hostname", "host", "tracker", "third_party_domain"])
    if domain_col is None:
        # Best-effort fallback: choose first non-count column.
        non_count_cols = [c for c in columns if c != count_col]
        if not non_count_cols:
            raise ValueError(f"Could not infer domain column in {path}. Found columns: {columns}")
        domain_col = non_count_cols[0]

    total_domains = len(rows)
    only_one = sum(1 for row in rows if parse_int(row.get(count_col)) == 1)

    ranked = sorted(
        [
            (str(row.get(domain_col, "")).strip(), parse_int(row.get(count_col)))
            for row in rows
            if str(row.get(domain_col, "")).strip()
        ],
        key=lambda x: (-x[1], x[0]),
    )[:5]

    return {
        "total_domains_receiving_addresses": total_domains,
        "contacted_by_only_one_wallet": only_one,
        "top_5_domains": ranked,
    }


def compute_presence_metrics(dataset_dir: Path, leaking_wallets_denominator: int) -> Dict[str, object]:
    """
    Reads tracker_presence/analytics_summary.csv and computes:
    - wallets_embedding_analytics_count
    - wallets_embedding_analytics_display

    Assumptions:
    - one row per wallet in the relevant subset
    - analytics_hits may exist
    - telemetry_hits may also exist
    - if both exist, a wallet is counted if either >= 1
    """
    path = dataset_dir / "analysis_result" / "tracker_presence" / "analytics_summary.csv"
    rows = read_csv(path)

    if not rows:
        return {
            "wallets_embedding_analytics_count": 0,
            "wallets_embedding_analytics_display_md": percent_str_md(0, leaking_wallets_denominator),
            "wallets_embedding_analytics_display_tex": percent_str(0, leaking_wallets_denominator),
        }

    columns = list(rows[0].keys())
    analytics_hits_col = find_column(columns, ["analytics_hits"])
    telemetry_hits_col = find_column(columns, ["telemetry_hits"])

    if analytics_hits_col is None and telemetry_hits_col is None:
        raise ValueError(
            f"Could not find analytics_hits or telemetry_hits in {path}. "
            f"Found columns: {columns}"
        )

    count = 0
    for row in rows:
        analytics_hits = parse_int(row.get(analytics_hits_col)) if analytics_hits_col else 0
        telemetry_hits = parse_int(row.get(telemetry_hits_col)) if telemetry_hits_col else 0
        if analytics_hits >= 1 or telemetry_hits >= 1:
            count += 1

    return {
        "wallets_embedding_analytics_count": count,
        "wallets_embedding_analytics_display_md": percent_str_md(count, leaking_wallets_denominator),
        "wallets_embedding_analytics_display_tex": percent_str(count, leaking_wallets_denominator),
    }


def compute_dataset_summary(base_dir: Path, dataset_name: str, latex_label: str) -> Dict[str, object]:
    dataset_dir = base_dir / dataset_name

    leak = compute_leak_metrics(dataset_dir)
    domains = compute_domain_metrics(dataset_dir)
    presence = compute_presence_metrics(dataset_dir, leak["to_any_endpoints"])

    return {
        "dataset_dir": dataset_name,
        "dataset_latex": latex_label,
        **leak,
        **domains,
        **presence,
    }


def write_summary_csv(output_path: Path, summaries: List[Dict[str, object]]) -> None:
    fieldnames = [
        "dataset_dir",
        "dataset_latex",
        "to_any_endpoints",
        "to_analytics_endpoints",
        "to_telemetry_endpoints",
        "total_domains_receiving_addresses",
        "contacted_by_only_one_wallet",
        "contacted_by_only_one_wallet_pct",
        "wallets_embedding_analytics_count",
        "wallets_embedding_analytics_display_md",
        "top_1",
        "top_2",
        "top_3",
        "top_4",
        "top_5",
    ]

    with output_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()

        for s in summaries:
            total_domains = int(s["total_domains_receiving_addresses"])
            only_one = int(s["contacted_by_only_one_wallet"])
            pct = percent_str_md(only_one, total_domains)

            top = s["top_5_domains"]
            row = {
                "dataset_dir": s["dataset_dir"],
                "dataset_latex": s["dataset_latex"],
                "to_any_endpoints": s["to_any_endpoints"],
                "to_analytics_endpoints": s["to_analytics_endpoints"],
                "to_telemetry_endpoints": s["to_telemetry_endpoints"],
                "total_domains_receiving_addresses": total_domains,
                "contacted_by_only_one_wallet": only_one,
                "contacted_by_only_one_wallet_pct": pct,
                "wallets_embedding_analytics_count": s["wallets_embedding_analytics_count"],
                "wallets_embedding_analytics_display_md": s["wallets_embedding_analytics_display_md"],
            }

            for i in range(5):
                if i < len(top):
                    row[f"top_{i+1}"] = f"{top[i][0]} ({top[i][1]})"
                else:
                    row[f"top_{i+1}"] = ""

            writer.writerow(row)


def write_summary_md(output_path: Path, summaries: List[Dict[str, object]]) -> None:
    headers = [
        "Metric",
        summaries[0]["dataset_dir"],
        summaries[1]["dataset_dir"],
        summaries[2]["dataset_dir"],
    ]

    def cell(s: Dict[str, object], key: str) -> str:
        return str(s[key])

    def top_domain(s: Dict[str, object], idx: int) -> str:
        top = s["top_5_domains"]
        if idx < len(top):
            return f"{top[idx][0]} ({top[idx][1]})"
        return ""

    lines = []
    lines.append(f"| {headers[0]} | {headers[1]} | {headers[2]} | {headers[3]} |")
    lines.append("|---|---:|---:|---:|")
    lines.append("| **Number of Wallets Leak Addresses** ||||")
    lines.append(
        f"| To any endpoints | {summaries[0]['to_any_endpoints']} | {summaries[1]['to_any_endpoints']} | {summaries[2]['to_any_endpoints']} |"
    )
    lines.append(
        f"| To analytics endpoints | {summaries[0]['to_analytics_endpoints']} | {summaries[1]['to_analytics_endpoints']} | {summaries[2]['to_analytics_endpoints']} |"
    )
    lines.append(
        f"| To telemetry endpoints | {summaries[0]['to_telemetry_endpoints']} | {summaries[1]['to_telemetry_endpoints']} | {summaries[2]['to_telemetry_endpoints']} |"
    )

    lines.append("| **Third-Party Domains Receiving Addresses** ||||")
    lines.append(
        f"| Total domains receiving addresses | {summaries[0]['total_domains_receiving_addresses']} | {summaries[1]['total_domains_receiving_addresses']} | {summaries[2]['total_domains_receiving_addresses']} |"
    )
    lines.append(
        f"| Contacted by only one wallet | {summaries[0]['contacted_by_only_one_wallet']} | {summaries[1]['contacted_by_only_one_wallet']} | {summaries[2]['contacted_by_only_one_wallet']} |"
    )
    lines.append(
        f"| Percentage contacted by only one wallet | "
        f"{percent_str_md(int(summaries[0]['contacted_by_only_one_wallet']), int(summaries[0]['total_domains_receiving_addresses']))} | "
        f"{percent_str_md(int(summaries[1]['contacted_by_only_one_wallet']), int(summaries[1]['total_domains_receiving_addresses']))} | "
        f"{percent_str_md(int(summaries[2]['contacted_by_only_one_wallet']), int(summaries[2]['total_domains_receiving_addresses']))} |"
    )

    lines.append("| **Analytics / Telemetry Presence in Wallets** ||||")
    lines.append(
        f"| # Wallets embedding analytics | "
        f"{summaries[0]['wallets_embedding_analytics_display_md']} | "
        f"{summaries[1]['wallets_embedding_analytics_display_md']} | "
        f"{summaries[2]['wallets_embedding_analytics_display_md']} |"
    )

    lines.append("| **Third-Party Domains Receiving Addresses (most contacted)** ||||")
    ranks = ["1st", "2nd", "3rd", "4th", "5th"]
    for i, rank in enumerate(ranks):
        lines.append(
            f"| {rank} | {top_domain(summaries[0], i)} | {top_domain(summaries[1], i)} | {top_domain(summaries[2], i)} |"
        )

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_latex_table(output_path: Path, summaries: List[Dict[str, object]]) -> None:
    s1, s2, s3 = summaries

    def top_domain(s: Dict[str, object], idx: int) -> str:
        top = s["top_5_domains"]
        if idx < len(top):
            domain, cnt = top[idx]
            return f"{latex_escape(domain)} ({cnt})"
        return ""

    tex = f"""\\begin{{table}}[t!]
\\centering
\\small

%--------------------------------------------------
% Block 1: All metrics except ranked domains
%--------------------------------------------------
\\begin{{tabular}}{{p{{4.5cm}}x{{0.9cm}}x{{0.9cm}}x{{0.9cm}}}}
\\toprule
\\textbf{{Metric}} &
\\textbf{{{s1['dataset_latex']}}} &
\\textbf{{{s2['dataset_latex']}}} &
\\textbf{{{s3['dataset_latex']}}} \\\\

\\midrule
\\multicolumn{{4}}{{l}}{{\\textbf{{Number of Wallets Leak Addresses}}}} \\\\
\\midrule
To any endpoints & {s1['to_any_endpoints']} & {s2['to_any_endpoints']} & {s3['to_any_endpoints']} \\\\
To analytics endpoints & {s1['to_analytics_endpoints']} & {s2['to_analytics_endpoints']} & {s3['to_analytics_endpoints']} \\\\
To telemetry endpoints & {s1['to_telemetry_endpoints']} & {s2['to_telemetry_endpoints']} & {s3['to_telemetry_endpoints']} \\\\

\\midrule
\\multicolumn{{4}}{{l}}{{\\textbf{{Third-Party Domains Receiving Addresses}}}} \\\\
\\midrule
Total domains receiving addresses & {s1['total_domains_receiving_addresses']} & {s2['total_domains_receiving_addresses']} & {s3['total_domains_receiving_addresses']} \\\\
Contacted by only one wallet & {s1['contacted_by_only_one_wallet']} & {s2['contacted_by_only_one_wallet']} & {s3['contacted_by_only_one_wallet']} \\\\
Percentage contacted by only one wallet &
{percent_str(int(s1['contacted_by_only_one_wallet']), int(s1['total_domains_receiving_addresses']))} &
{percent_str(int(s2['contacted_by_only_one_wallet']), int(s2['total_domains_receiving_addresses']))} &
{percent_str(int(s3['contacted_by_only_one_wallet']), int(s3['total_domains_receiving_addresses']))} \\\\

\\midrule
\\multicolumn{{4}}{{l}}{{\\textbf{{Analytics / Telemetry Presence in Wallets}}}} \\\\
\\midrule
\\# Wallets embedding analytics &
{s1['wallets_embedding_analytics_display_tex']} &
{s2['wallets_embedding_analytics_display_tex']} &
{s3['wallets_embedding_analytics_display_tex']} \\\\
\\midrule
\\end{{tabular}}


%--------------------------------------------------
% Block 2: Ranked third-party domains (independent width)
%--------------------------------------------------
\\begin{{tabular}}{{lx{{2.2cm}}x{{2.2cm}}x{{2.3cm}}}}
\\multicolumn{{4}}{{l}}{{\\textbf{{Third-Party Domains Receiving Addresses (most contacted)}}}} \\\\

\\midrule
1st &
{top_domain(s1, 0)} & {top_domain(s2, 0)} & {top_domain(s3, 0)} \\\\
2nd &
{top_domain(s1, 1)} & {top_domain(s2, 1)} & {top_domain(s3, 1)} \\\\
3rd &
{top_domain(s1, 2)} & {top_domain(s2, 2)} & {top_domain(s3, 2)} \\\\
4th &
{top_domain(s1, 3)} & {top_domain(s2, 3)} & {top_domain(s3, 3)} \\\\
5th &
{top_domain(s1, 4)} & {top_domain(s2, 4)} & {top_domain(s3, 4)} \\\\

\\bottomrule
\\end{{tabular}}

\\vspace{{1em}}
\\caption{{Cross-dataset comparison of address exposure and third-party connectivity across legacy ({s1['dataset_latex']}, {s2['dataset_latex']}) and contemporary ({s3['dataset_latex']}) browser-wallet datasets.}}
\\label{{tab:3-datasets-comparison}}
\\end{{table}}
"""
    output_path.write_text(tex, encoding="utf-8")


def main() -> None:
    script_dir = Path(__file__).resolve().parent
    base_dir = script_dir.parent
    output_dir = base_dir / OUTPUT_DIR
    output_dir.mkdir(parents=True, exist_ok=True)

    summaries = []
    for dataset_name, latex_label in DATASETS:
        summaries.append(compute_dataset_summary(base_dir, dataset_name, latex_label))

    # write_summary_csv(output_dir / "table1_summary.csv", summaries)
    # write_summary_md(output_dir / "table1_summary.md", summaries)
    write_latex_table(output_dir / "table1_reproduced.tex", summaries)

    print("Generated:")
    # print(f"  {output_dir / 'table1_summary.csv'}")
    # print(f"  {output_dir / 'table1_summary.md'}")
    print(f"  {output_dir / 'table1_reproduced.tex'}")


if __name__ == "__main__":
    main()