/******** COMPLETELY GENERATED BY AI */

/* log.ts — tiny structured logger for Playwright/Node, no deps */

/* NO imports (avoid name conflicts like `config`) */

type Level =
  | "debug"
  | "step"
  | "screen"
  | "click"
  | "action"
  | "info"
  | "success"
  | "warn"
  | "error"
  | "banner";

type LogMeta = Record<string, unknown> | undefined;

export type LoggerOptions = {
  scope?: string; // e.g., "metamask", "onboarding", "page:welcome"
  useColors?: boolean; // default: true (disabled if NO_COLOR or not TTY)
  useEmoji?: boolean; // default: true
  showTimestamp?: boolean; // default: true
  json?: boolean; // default: from env LOG_JSON
  minLevel?: Level; // default: from env LOG_LEVEL (info)
  include?: string[]; // match against "scope" or message
  exclude?: string[]; // same as include, takes precedence
  bannerSteps?: boolean; // default: true -> show banner lines
  indentInSteps?: boolean; // default: true -> indent logs inside steps
  showStepIds?: boolean; // default: true -> prepend [S#] to lines inside steps
};

const DEFAULTS: Required<
  Omit<LoggerOptions, "scope" | "include" | "exclude" | "minLevel">
> = {
  useColors: true,
  useEmoji: true,
  showTimestamp: true,
  json: envFlag("LOG_JSON", false),
  bannerSteps: true,
  indentInSteps: true,
  showStepIds: true,
};

// Level ordering for filtering
const ORDER: Record<Level, number> = {
  debug: 10,
  step: 20,
  screen: 25,
  click: 27,
  action: 28,
  info: 30,
  success: 40,
  warn: 50,
  error: 60,
  banner: 70,
};

// Resolve min level from env
function envMinLevel(): Level {
  const v = (process.env.LOG_LEVEL || "").toLowerCase() as Level;
  return v && ORDER[v] ? v : "info";
}

// Env helpers
function envList(name: string): string[] | undefined {
  const raw = process.env[name];
  if (!raw) return undefined;
  return raw
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}
function envFlag(name: string, fallback = false): boolean {
  const v = process.env[name];
  if (!v) return fallback;
  return ["1", "true", "yes", "on"].includes(v.toLowerCase());
}

// Basic ANSI colors (no external deps)
const TTY = !!process.stdout.isTTY;
const NO_COLOR = !!process.env.NO_COLOR;
const supportsColor = TTY && !NO_COLOR;

const c = (open: number, close: number) => (s: string) =>
  `\u001b[${open}m${s}\u001b[${close}m`;

const colors = {
  gray: c(90, 39),
  dim: c(2, 22),
  bold: c(1, 22),
  red: c(31, 39),
  green: c(32, 39),
  yellow: c(33, 39),
  blue: c(34, 39),
  magenta: c(35, 39),
  cyan: c(36, 39),
  white: c(97, 39),
};

const SYMBOLS: Record<Level, string> = {
  debug: "🔧",
  step: "🧭",
  screen: "🪟",
  click: "🖱️",
  action: "⚙️",
  info: "ℹ️",
  success: "✅",
  warn: "⚠️",
  error: "🛑",
  banner: "",
};

const LEVEL_COLOR: Record<Level, (s: string) => string> = {
  debug: colors.gray,
  step: colors.cyan,
  screen: colors.blue,
  click: colors.magenta,
  action: colors.white,
  info: colors.white,
  success: colors.green,
  warn: colors.yellow,
  error: colors.red,
  banner: colors.white,
};

export interface Logger {
  // core
  log(level: Level, msg: string, meta?: LogMeta): void;

  // convenience methods
  debug(msg: string, meta?: LogMeta): void;
  step(msg: string, meta?: LogMeta): void;
  screen(msg: string, meta?: LogMeta): void;
  click(msg: string, meta?: LogMeta): void;
  action(msg: string, meta?: LogMeta): void;
  info(msg: string, meta?: LogMeta): void;
  success(msg: string, meta?: LogMeta): void;
  warn(msg: string, meta?: LogMeta): void;
  error(msg: string, meta?: LogMeta): void;
  banner(msg: string, meta?: LogMeta): void;

  // step lifecycle (stack-based)
  stepStart(msg: string, meta?: LogMeta): void;
  stepEnd(meta?: LogMeta): void;
  stepFail(err?: unknown, meta?: LogMeta): void;
  runStep<T>(msg: string, fn: () => Promise<T> | T, meta?: LogMeta): Promise<T>;

  // scoping
  child(scope: string, opts?: Partial<LoggerOptions>): Logger;

  // runtime controls
  isEnabled(level: Level, msg?: string): boolean;
  setMinLevel(level: Level): void;
}

export function createLogger(opts: LoggerOptions = {}): Logger {
  const cfg = normalizeOptions(opts);

  // step state (scoped inside the factory so helpers can see `cfg`)
  let stepCounter = 0;
  type StepFrame = { id: number; msg: string; t0: number };
  const stepStack: StepFrame[] = [];

  function bannerLine(): string {
    const line = "─────────────────────────────────────────────────────";
    return cfg.useColors && supportsColor
      ? colors.dim(line) + "\n"
      : line + "\n";
  }

  // core formatting
  function fmt(level: Level, msg: string, meta?: LogMeta) {
    const ts = cfg.showTimestamp ? new Date().toISOString() : undefined;
    const scope = cfg.scope;
    const emoji = cfg.useEmoji ? SYMBOLS[level] : undefined;
    const levelLabel = level.toUpperCase();

    if (cfg.json) {
      const payload: any = { time: ts, level, msg };
      if (scope) payload.scope = scope;
      if (meta && Object.keys(meta).length) payload.meta = meta;
      return JSON.stringify(payload);
    }

    const colorize =
      cfg.useColors && supportsColor ? LEVEL_COLOR[level] : (s: string) => s;
    const parts = [
      cfg.showTimestamp ? colors.dim(`[${ts}]`) : undefined,
      scope ? colors.bold(`[${scope}]`) : undefined,
      colorize(emoji ? `${emoji} ${levelLabel}` : levelLabel),
      "-",
      msg,
    ].filter(Boolean);

    // decorate non-step logs if inside a step
    if (
      !cfg.json &&
      level !== "step" &&
      stepStack.length > 0 &&
      cfg.showStepIds
    ) {
      const current = stepStack[stepStack.length - 1];
      if (current) {
        parts.splice(2, 0, colors.dim(`[S${current.id}]`)); // after scope, before level label
      }
    }

    let line = parts.join(" ");

    // indent logs that occur while a step is open
    if (
      !cfg.json &&
      cfg.indentInSteps &&
      level !== "step" &&
      stepStack.length > 0
    ) {
      const indent = "  ".repeat(stepStack.length);
      line = line.replace(" - ", " - " + indent);
    }

    if (meta && Object.keys(meta).length) {
      const tail = stringifyMeta(meta);
      line += " " + (cfg.useColors && supportsColor ? colors.dim(tail) : tail);
    }
    return line;
  }

  function matchesFilters(level: Level, msg?: string): boolean {
    if (ORDER[level] < ORDER[cfg.minLevel]) return false;
    const keyspace = [cfg.scope, msg].filter(Boolean).join(" ");
    if (cfg.exclude?.some((p) => keyspace.includes(p))) return false;
    if (cfg.include && cfg.include.length > 0) {
      return cfg.include.some((p) => keyspace.includes(p));
    }
    return true;
  }

  function out(level: Level, line: string) {
    const stream =
      level === "error" || level === "warn" ? process.stderr : process.stdout;
    stream.write(line + "\n");
  }

  function log(level: Level, msg: string, meta?: LogMeta) {
    if (!matchesFilters(level, msg)) return;
    out(level, fmt(level, msg, meta));
  }

  // write a line that’s visually nested under a step
  function lineWithinStep(
    level: Level,
    frame: StepFrame,
    msg: string,
    meta?: LogMeta
  ) {
    if (cfg.json) {
      const merged = { stepId: frame.id, ...(meta || {}) };
      log(level, msg, merged);
      return;
    }
    const tag = cfg.showStepIds ? colors.dim(`[S${frame.id}]`) + " " : "";
    const indent = cfg.indentInSteps ? "  ".repeat(stepStack.length) : "";
    const formatted = fmt(level, `${tag}${msg}`, meta);
    const withIndent = formatted.replace(" - ", " - " + indent);
    out(level, withIndent);
  }

  // step lifecycle
  function stepStart(msg: string, meta?: LogMeta) {
    const id = ++stepCounter;
    const t0 = Date.now();
    const frame: StepFrame = { id, msg, t0 };
    stepStack.push(frame);

    if (cfg.bannerSteps && !cfg.json) out("info", bannerLine());
    const prefix = cfg.json ? "" : `STEP #${id}  `;
    log("step", prefix + msg, meta);
  }

  function stepEnd(additional?: LogMeta) {
    const s = stepStack.pop();
    if (!s) {
      log("warn", "stepEnd() called without a matching stepStart()");
      return;
    }
    const ms = Date.now() - s.t0;
    lineWithinStep("success", s, `${s.msg} (${ms}ms)`, additional ?? {});
    if (cfg.bannerSteps && !cfg.json) out("info", bannerLine());
  }

  function stepFail(err?: unknown, additional?: LogMeta) {
    const s = stepStack.pop();
    if (!s) {
      log("warn", "stepFail() called without a matching stepStart()", {
        error: serializeError(err),
      });
      return;
    }
    const ms = Date.now() - s.t0;
    const metaErr: Record<string, unknown> = {
      ...additional,
      error: serializeError(err),
      durationMs: ms,
    };
    lineWithinStep("error", s, `${s.msg} (${ms}ms)`, metaErr);
    if (cfg.bannerSteps && !cfg.json) out("info", bannerLine());
  }

  async function runStep<T>(
    msg: string,
    fn: () => Promise<T> | T,
    meta?: LogMeta
  ): Promise<T> {
    stepStart(msg, meta);
    try {
      const result = await fn();
      stepEnd();
      return result;
    } catch (err) {
      stepFail(err);
      throw err;
    }
  }

  function child(scope: string, more?: Partial<LoggerOptions>): Logger {
    return createLogger({
      ...cfg,
      ...more,
      scope: cfg.scope ? `${cfg.scope}:${scope}` : scope,
    });
  }

  function isEnabled(level: Level, msg?: string) {
    return matchesFilters(level, msg);
  }

  function setMinLevel(level: Level) {
    (cfg as any).minLevel = level;
  }

  const api: Logger = {
    log,
    debug: (m, meta) => log("debug", m, meta),
    step: (m, meta) => log("step", m, meta),
    screen: (m, meta) => log("screen", m, meta),
    click: (m, meta) => log("click", m, meta),
    action: (m, meta) => log("action", m, meta),
    info: (m, meta) => log("info", m, meta),
    success: (m, meta) => log("success", m, meta),
    warn: (m, meta) => log("warn", m, meta),
    error: (m, meta) => log("error", m, meta),
    banner: (m) => {
      console.log(
        "╭──────────────────────────────────────────────────────────────╮"
      );
      console.log(`|               ${m}                  |`);
      console.log(
        "╰──────────────────────────────────────────────────────────────╯"
      );
    },

    stepStart,
    stepEnd,
    stepFail,
    runStep,

    child,
    isEnabled,
    setMinLevel,
  };

  return api;
}

/* ---------- helpers ---------- */

function normalizeOptions(opts: LoggerOptions) {
  const base: any = {
    ...DEFAULTS,
    scope: opts.scope,
    useColors: opts.useColors ?? DEFAULTS.useColors,
    useEmoji: opts.useEmoji ?? DEFAULTS.useEmoji,
    showTimestamp: opts.showTimestamp ?? DEFAULTS.showTimestamp,
    json: typeof opts.json === "boolean" ? opts.json : DEFAULTS.json,
    minLevel: opts.minLevel ?? envMinLevel(),
    include: opts.include ?? envList("LOG_INCLUDE"),
    exclude: opts.exclude ?? envList("LOG_EXCLUDE"),
    bannerSteps: opts.bannerSteps ?? DEFAULTS.bannerSteps,
    indentInSteps: opts.indentInSteps ?? DEFAULTS.indentInSteps,
    showStepIds: opts.showStepIds ?? DEFAULTS.showStepIds,
  };
  if (!supportsColor) base.useColors = false;
  return base as Required<LoggerOptions>;
}

function stringifyMeta(meta: LogMeta): string {
  try {
    return JSON.stringify(meta);
  } catch {
    return "[meta:unserializable]";
  }
}

function serializeError(err: unknown) {
  if (!err) return undefined;
  if (err instanceof Error) {
    return { name: err.name, message: err.message, stack: err.stack };
  }
  return err;
}
