#!/usr/bin/env python3

# Fully generated by chatgpt

from __future__ import annotations

import csv
import sys
from pathlib import Path
from typing import Dict, List, Optional

max_int = sys.maxsize
while True:
    try:
        csv.field_size_limit(max_int)
        break
    except OverflowError:
        max_int = int(max_int / 10)


INPUT_FILE = "2)-dApps-behavior-summary.csv"
OUTPUT_DIR = "../reproduced_tables"


def read_csv(path: Path) -> List[Dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"Missing file: {path}")

    with path.open("r", encoding="utf-8-sig", newline="") as f:
        sample = f.read(4096)
        f.seek(0)

        try:
            dialect = csv.Sniffer().sniff(sample, delimiters=",;\t")
        except csv.Error:
            dialect = csv.excel
            dialect.delimiter = ","

        return list(csv.DictReader(f, dialect=dialect))


def find_column(columns: List[str], candidates: List[str]) -> Optional[str]:
    lowered = {c.strip().lower(): c for c in columns}
    for candidate in candidates:
        if candidate.strip().lower() in lowered:
            return lowered[candidate.strip().lower()]
    return None


def normalize_boolish(value: object) -> bool:
    if value is None:
        return False
    s = str(value).strip().lower()
    return s in {"1", "true", "yes", "y", "t"}


def parse_int(value: object, default: int = 0) -> int:
    if value is None:
        return default
    s = str(value).strip()
    if s == "":
        return default
    try:
        return int(float(s))
    except ValueError:
        return default


def pct_str(count: int, total: int) -> str:
    if total == 0:
        return "(0/0) 0.0%"
    return f"({count}/{total}) {(count / total) * 100:.1f}%"


def pct_str_tex(count: int, total: int) -> str:
    if total == 0:
        return "(0/0) 0.0\\%"
    return f"({count}/{total}) {(count / total) * 100:.1f}\\%"


def compute_summary(rows: List[Dict[str, str]]) -> Dict[str, object]:
    if not rows:
        raise ValueError("Input CSV is empty.")

    columns = list(rows[0].keys())

    revoke_col = find_column(columns, ["revokePermission", "revokePermissions"])
    accounts_before_col = find_column(columns, ["eth_accounts_beforeRequest"])
    localstorage_col = find_column(columns, ["localStorage"])
    stored_at_end_col = find_column(columns, ["walletStoredAtEnd"])
    tracker_count_col = find_column(columns, ["tracker_count"])

    missing = []
    for name, col in [
        ("revokePermission", revoke_col),
        ("eth_accounts_beforeRequest", accounts_before_col),
        ("localStorage", localstorage_col),
        ("walletStoredAtEnd", stored_at_end_col),
        ("tracker_count", tracker_count_col),
    ]:
        if col is None:
            missing.append(name)

    if missing:
        raise ValueError(f"Missing expected columns: {', '.join(missing)}. Found columns: {columns}")

    total_dapps = len(rows)

    no_revoke = sum(1 for r in rows if not normalize_boolish(r.get(revoke_col)))
    eth_accounts_before = sum(1 for r in rows if normalize_boolish(r.get(accounts_before_col)))
    stores_local = sum(1 for r in rows if normalize_boolish(r.get(localstorage_col)))

    not_clear_logout = sum(
        1
        for r in rows
        if normalize_boolish(r.get(localstorage_col)) and normalize_boolish(r.get(stored_at_end_col))
    )

    tracker_ge_1 = sum(1 for r in rows if parse_int(r.get(tracker_count_col)) >= 1)
    tracker_ge_3 = sum(1 for r in rows if parse_int(r.get(tracker_count_col)) >= 3)

    return {
        "total_dapps": total_dapps,
        "do_not_invoke_revokePermissions_count": no_revoke,
        "do_not_invoke_revokePermissions_pct": pct_str(no_revoke, total_dapps),
        "calls_eth_accounts_before_permission_count": eth_accounts_before,
        "calls_eth_accounts_before_permission_pct": pct_str(eth_accounts_before, total_dapps),
        "stores_address_localstorage_count": stores_local,
        "stores_address_localstorage_pct": pct_str(stores_local, total_dapps),
        "do_not_clear_stored_address_count": not_clear_logout,
        "do_not_clear_stored_address_pct": pct_str(not_clear_logout, stores_local),
        "contacts_ge_1_tracker_count": tracker_ge_1,
        "contacts_ge_1_tracker_pct": pct_str(tracker_ge_1, total_dapps),
        "contacts_ge_3_trackers_count": tracker_ge_3,
        "contacts_ge_3_trackers_pct": pct_str(tracker_ge_3, total_dapps),
    }


def write_summary_csv(path: Path, summary: Dict[str, object]) -> None:
    rows = [
        {
            "behavior": r"Do not invoke wallet_revokePermissions",
            "count": summary["do_not_invoke_revokePermissions_count"],
            "percentage": summary["do_not_invoke_revokePermissions_pct"],
        },
        {
            "behavior": r"Calls eth_accounts before permission",
            "count": summary["calls_eth_accounts_before_permission_count"],
            "percentage": summary["calls_eth_accounts_before_permission_pct"],
        },
        {
            "behavior": r"Stores address in localStorage/cookies",
            "count": summary["stores_address_localstorage_count"],
            "percentage": summary["stores_address_localstorage_pct"],
        },
        {
            "behavior": r"Do not clear stored address on logout (of stored-address dApps)",
            "count": summary["do_not_clear_stored_address_count"],
            "percentage": summary["do_not_clear_stored_address_pct"],
        },
        {
            "behavior": r"Contacts >=1 third-party tracker",
            "count": summary["contacts_ge_1_tracker_count"],
            "percentage": summary["contacts_ge_1_tracker_pct"],
        },
        {
            "behavior": r"Contacts >=3 trackers",
            "count": summary["contacts_ge_3_trackers_count"],
            "percentage": summary["contacts_ge_3_trackers_pct"],
        },
    ]

    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["behavior", "count", "percentage"])
        writer.writeheader()
        writer.writerows(rows)


def write_summary_md(path: Path, summary: Dict[str, object]) -> None:
    lines = [
        "| Behavior | Count | Percentage |",
        "|---|---:|---:|",
        f"| Do not invoke `wallet_revokePermissions` | {summary['do_not_invoke_revokePermissions_count']} | {summary['do_not_invoke_revokePermissions_pct']} |",
        f"| Calls `eth_accounts` before permission | {summary['calls_eth_accounts_before_permission_count']} | {summary['calls_eth_accounts_before_permission_pct']} |",
        f"| Stores address in localStorage/cookies | {summary['stores_address_localstorage_count']} | {summary['stores_address_localstorage_pct']} |",
        f"| Do not clear stored address on logout (of {summary['stores_address_localstorage_count']}) | {summary['do_not_clear_stored_address_count']} | {summary['do_not_clear_stored_address_pct']} |",
        f"| Contacts >=1 third-party tracker | {summary['contacts_ge_1_tracker_count']} | {summary['contacts_ge_1_tracker_pct']} |",
        f"| Contacts >=3 trackers | {summary['contacts_ge_3_trackers_count']} | {summary['contacts_ge_3_trackers_pct']} |",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def write_latex_table(path: Path, summary: Dict[str, object]) -> None:
    tex = f"""\\begin{{table}}[t]
  \\centering
  \\small
  \\begin{{tabular}}{{lcc}}
    \\toprule
    \\textbf{{Behavior}} & \\textbf{{Count}} & \\textbf{{Percentage}} \\\\
    \\midrule
    Do not invoke \\revokePermissions{{}} & {summary['do_not_invoke_revokePermissions_count']} & {pct_str_tex(summary['do_not_invoke_revokePermissions_count'], summary['total_dapps'])} \\\\
    Calls \\ethAccounts{{}} before permission & {summary['calls_eth_accounts_before_permission_count']} & {pct_str_tex(summary['calls_eth_accounts_before_permission_count'], summary['total_dapps'])} \\\\
    Stores address in localStorage/cookies & {summary['stores_address_localstorage_count']} & {pct_str_tex(summary['stores_address_localstorage_count'], summary['total_dapps'])} \\\\
    Do not clear stored address on logout (of {summary['stores_address_localstorage_count']}) & {summary['do_not_clear_stored_address_count']} & {pct_str_tex(summary['do_not_clear_stored_address_count'], summary['stores_address_localstorage_count'])} \\\\
    Contacts $\\geq$1 third-party tracker & {summary['contacts_ge_1_tracker_count']} & {pct_str_tex(summary['contacts_ge_1_tracker_count'], summary['total_dapps'])} \\\\
    Contacts $\\geq$3 trackers & {summary['contacts_ge_3_trackers_count']} & {pct_str_tex(summary['contacts_ge_3_trackers_count'], summary['total_dapps'])} \\\\
    \\bottomrule
  \\end{{tabular}}
  \\vspace{{1em}}
  \\caption{{Summary of permission- and tracking-related behaviors observed across {summary['total_dapps']} popular Ethereum dApps.}}
  \\label{{tab:dapp-summary}}
  \\vspace{{-3em}}
\\end{{table}}
"""
    path.write_text(tex, encoding="utf-8")


def main() -> None:
    script_dir = Path(__file__).resolve().parent
    input_path = script_dir / INPUT_FILE
    output_dir = script_dir / OUTPUT_DIR
    output_dir.mkdir(parents=True, exist_ok=True)

    rows = read_csv(input_path)
    summary = compute_summary(rows)

    # write_summary_csv(output_dir / "table4_summary.csv", summary)
    # write_summary_md(output_dir / "table4_summary.md", summary)
    write_latex_table(output_dir / "table4_reproduced.tex", summary)

    print("Generated:")
    # print(f"  {output_dir / 'table4_summary.csv'}")
    # print(f"  {output_dir / 'table4_summary.md'}")
    print(f"  {output_dir / 'table4_reproduced.tex'}")


if __name__ == "__main__":
    main()